name: Maja the Maltese Angel
favicon: null
layout_spectrum: 0.0765903852880001
typography_spectrum: 0.8415206403005868
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.39152077212929726
  lightness: 0.1569910377729684
  saturation: 0.5007934384047985
  rhythmicContrast: 0.07409958401694894
purpose: []
